archive/urls.py
from django.contrib import admin
from django.urls import path, include
from quotes import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('quotes/',include('quotes.urls')),
    path('',views.all_quotes)
]

quotes/urls.py
from django.urls import path
from . import views

app_name = 'quotes'

urlpatterns=[
    path('',views.all_quotes, name="all_quotes"),
    path('add_quote',views.add_quote,name='add_quote'),
    path('add_quote_action',views.add_quote_action,name='add_quote_action'),
    path('quote_details/<pk>',views.quote_details,name='quote_details'),
    path('delete_quote/<pk>',views.delete,name='delete'),
    path('edit_quote/<pk>',views.edit_quote,name='edit_quote'),
    path('search',views.search_quote,name='search_quote')
]

quotes/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.



class Quote(models.Model):
    class Genre(models.TextChoices):
        General = "General","General"
        Love = "Love","Love"
        Economy = "Economy","Economy"
        Education = "Education","Education"
    #user = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=100, null=False)
    quoted_by = models.CharField(max_length=100, null=False,blank=True)
    image = models.ImageField(null=True, blank=True, default='/anonymous.jpeg')
    created_time = models.DateTimeField(auto_now_add=True)
    type = models.CharField(max_length = 50, null=False,default=Genre.General, choices=Genre.choices)
    description = models.CharField(max_length=500,null=True,blank=True)

    def __str__(self):
        return self.title
    

quotes/forms.py
from django.forms import ModelForm
from .models import Quote
from django.contrib.auth.models import User

class QuoteForm(ModelForm):
    class Meta:
        model = Quote
        fields = ['title','quoted_by', 'image', 'type', 'description']

    def clean_quoted_by(self):
        quoted_by = self.cleaned_data['quoted_by']
        return quoted_by or 'anonymous'
        

quotes/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from quotes.models import Quote
from quotes.forms import QuoteForm
from django.contrib import messages

# Create your views here.

def add_quote(request):
    context = {
        'quoteform':QuoteForm()
    }
    return render(request,'addquote.html',context)

def all_quotes(request):
    quotes_list = Quote.objects.all()
    context = {
        'quotes_list': quotes_list,
    }
    return render(request,'quotes.html',context)

def add_quote_action(request):
    quoteform = QuoteForm(request.POST, request.FILES)
    if quoteform.is_valid():
        quoteform.save()
        messages.success(request,'Added Successfully')
        return redirect('quotes:all_quotes')
    context = {
            'quoteform': quoteform,
        }
    return render(request, 'addquote.html', context)

def quote_details(request, pk):
    single_quote = Quote.objects.get(id=pk)
    context = {
        'single_quote': single_quote
    }
    return render(request,'quote_details.html',context)

def edit_quote(request,pk):
    quote = Quote.objects.get(id=pk)
    if request.POST:
        quote.title = request.POST.get('title')
        quote.quoted_by = request.POST.get('quoted_by')
        quote.description = request.POST.get('description')
        quote.type = request.POST.get('type')
        quote.image = request.POST.get('image')
        try:
            quote.save()
            messages.success(request, 'Saved Successfully')
            return redirect('quotes:quote_details', quote.id)
        except:
            messages.error(request, 'Could not save, wrong values provided')
            quote = Quote.objects.get(id=pk)
    context = {
            'quote':quote,
            'edit_quote':True,
            'types': ['General', 'Love', 'Economy', 'Education']
        }
    return render(request,'quote_details.html',context)    

def delete(request,pk):
    quote_to_delete = Quote.objects.get(id=pk)
    quote_to_delete.delete()
    messages.success(request,'quote deleted')
    return redirect('quotes:all_quotes')

def search_quote(request):
    if 'word' in request.GET:
        found_quote = request.GET['word']
        quotes_list = Quote.objects.filter(title__icontains = found_quote)
        context = {
                'quotes_list':quotes_list
            }
    return render(request,'quotes.html',context)

quotes/templates/addquote.html
{% extends "base.html" %}
{% block content %}

<form action="{% url 'quotes:add_quote_action' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{ quoteform.as_table }}
    </table>
    <input type="submit" value="Add">
</form>

{% endblock %}

quotes/templates/quote_details.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<div>
    <a class="btn btn-success" href="{% url 'quotes:all_quotes' %}"> back home</a>
</div>

{% if edit_quote %}

    <form action="{% url 'quotes:edit_quote' quote.id %}" method="POST">
        {% csrf_token %}
        <div>
            title <input type="text" name="title" value="{{ quote.title }}" required/>
        </div>
        <div>
            quoted_by <input type="text" name="quoted_by" value="{{ quote.quoted_by }}" required/>
        </div>
        <div>
            type
            <select name="type" required>
            {% for type in types %}
                {% if quote.type == type %}
                    <option value="{{type}}" selected>{{type}}</option>
                {% else %}
                    <option value="{{type}}">{{type}}</option>
                {% endif %}
            {% endfor %}
            </select>
        </div>
        <div>
            description <input type="text" name="description" value="{{ quote.description}}"/>
        </div>
        <div>
             <img style="width:150px;height:150px" src="{% static 'images/' %}{{ quote.image }}" class="card-img-top" alt="...">
        </div>
        <div>
            <input type="file" name="image" />
        </div>
        <input type="submit" value="Save">
    </form>
   

    
{% else %}

{% if messages %}
    {%for message in messages%}
        <div> {{message}} </div>
    {% endfor %}

{% endif%}

    <div>
        <div>
            <img style="width:150px;height:150px" src="{ static 'images/' }{{ single_quote.image }}" class="card-img-top" alt="...">
        </div>
        <div>{{ single_quote.title }}</div>
    
        <div>{{single_quote.quoted_by}}</div>
        <div>{{single_quote.type}}</div>

        <div>{{single_quote.description}}</div>
        

    </div>
{% endif %}
{% endblock %}

quotes/templates/quotes.html
{% extends "base.html" %}
{% load static %}
{% block content %}


{% if messages %}
  {% for message in messages %}
    {{ message }}
  {% endfor %}
{% endif %}


<div class="row row-cols-1 row-cols-md-5 g-4">
  {% if quotes_list|length > 0 %}
    {% for quote in quotes_list %}    
    <div class="col">
      <div class="card">
        <a href="{% url 'quotes:quote_details' quote.id %}">
          <img style="width:150px;height:150px" src="{% static 'images/' %}{{ quote.image }}" class="card-img-top" alt="...">
        </a>
        <div class="card-body">
          <h5 class="card-title">{{ quote.title }} {{ stam }}</h5>
          <p class="card-text"> {{ quote.quoted_by }}</p>
          <p class="card-text"> {{quote.type}}</p>
          <a class="btn btn-danger" href="{% url 'quotes:delete' quote.id %}" onclick="confirm('are you sure you want to delete this quote?');">delete</a>
          <a class="btn btn-info" href="{% url 'quotes:edit_quote' quote.id %}">Edit</a>
         <!--{% if quote.user == user%}-->
         <!--{% endif %}-->
        </div>
      </div>
    </a>
    </div>
    {% endfor %}
    {% else %}
      <div>No quotes found</div>
    {% endif %}
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Quotes</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'quotes:add_quote' %}">Add a quote</a>
            </li>
          </ul>
          <!-- login register -->
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">    
              <li><span>Hello! &nbsp;</span>
              <li><a href="/">Log Out</a>
          </ul>
          <!-- end login register-->

            <form class="d-flex" role="search" action = "{% url 'quotes:search_quote' %}">
              <input name="word" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
      
        </div>
      </div>
      </nav>
{% block title %} {% endblock %}
{% block content %}
{% endblock %}
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>